module.exports = {
  vehicles: {
    sultan: "sultan",
    kuruma: "kuruma",
    adder: "adder",
    zentorno: "zentorno",
    entityxf: "entityxf",
    t20: "t20",
    osiris: "osiris",
    x80: "x80proto",
    vagner: "vagner",
    deveste: "deveste",
    thrax: "thrax",
    emerus: "emerus",
    kreiger: "kreiger",
    s80: "s80",
    pariah: "pariah",
    italigtb: "italigtb",
    italigtb2: "italigtb2",
    nero: "nero",
    nero2: "nero2",
    tempesta: "tempesta",
    reaper: "reaper",
    fmj: "fmj",
    bullet: "bullet",
    cheetah: "cheetah",
    comet: "comet",
    comet2: "comet2",
    comet3: "comet3",
    comet4: "comet4",
    comet5: "comet5",
    comet6: "comet6",
    comet7: "comet7",
    elegy: "elegy",
    elegy2: "elegy2",
    massacro: "massacro",
    massacro2: "massacro2",
    jester: "jester",
    jester2: "jester2",
    jester3: "jester3",
    turismo: "turismo",
    infernus: "infernus",
    vacca: "vacca",
    dominator: "dominator",
    dominator2: "dominator2",
    dominator3: "dominator3",
    gauntlet: "gauntlet",
    gauntlet2: "gauntlet2",
    gauntlet3: "gauntlet3",
    gauntlet4: "gauntlet4",
    gauntlet5: "gauntlet5",
    bati: "bati",
    bati2: "bati2",
    hakuchou: "hakuchou",
    hakuchou2: "hakuchou2",
    double: "double",
    fcr: "fcr",
    fcr2: "fcr2",
    sanchez: "sanchez",
    sanchez2: "sanchez2",
    bf400: "bf400",
    faggio: "faggio",
    faggio2: "faggio2",
    faggio3: "faggio3",
  },

  // Vehicle spawn settings
  spawnSettings: {
    distance: 3,
    numberPlate: "RAGE",
    locked: false,
    engine: true,
  },

  // Rental vehicle settings
  rentalSettings: {
    vehicles: ["faggio"],
    duration: 200,
    numberPlate: "RENTAL",
    color: [
      [255, 0, 0],
      [255, 0, 0],
    ],
  },
};
